# Generated by Django 5.2.16 on 2026-07-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_email_case_insensitive"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("password_hash", models.CharField(max_length=128)),
                ("code_hash", models.CharField(max_length=128)),
                ("sent_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                (
                    "failed_attempts",
                    models.PositiveSmallIntegerField(default=0),
                ),
            ],
            options={
                "verbose_name": "pending registration",
                "verbose_name_plural": "pending registrations",
            },
        ),
    ]
