# Generated by Django 5.2.16 on 2026-08-30 11:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('format', models.CharField(choices=[('epub', 'EPUB'), ('pdf', 'PDF')], max_length=4)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=7)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='processing', max_length=10)),
                ('storage_key', models.CharField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='KnowledgeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.CharField(blank=True, help_text='Логический ключ будущего объекта в хранилище.', max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'knowledge profile',
                'verbose_name_plural': 'knowledge profiles',
            },
        ),
        migrations.CreateModel(
            name='UserLibraryBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_location', models.JSONField(blank=True, default=dict)),
                ('reading_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_entries', to='knowledge.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_library_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'library book',
                'verbose_name_plural': 'library books',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(condition=models.Q(('format__in', ('epub', 'pdf'))), name='knowledge_book_format_valid'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(condition=models.Q(('visibility__in', ('public', 'private'))), name='knowledge_book_visibility_valid'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('processing', 'ready', 'failed'))), name='knowledge_book_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='userlibrarybook',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='knowledge_library_user_book_unique'),
        ),
        migrations.AddConstraint(
            model_name='userlibrarybook',
            constraint=models.CheckConstraint(condition=models.Q(('reading_percentage__gte', 0), ('reading_percentage__lte', 100)), name='knowledge_library_percentage_range'),
        ),
    ]
