# Generated by Django 5.2.16 on 2026-09-11 22:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_storagecleanupjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_basis',
            field=models.CharField(blank=True, choices=[('author', 'Автор произведения'), ('authorized_distributor', 'Правообладатель или уполномоченный распространитель')], editable=False, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='rights_confirmed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='rights_statement_version',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('publication_basis__isnull', True), ('rights_confirmed_at__isnull', True), ('rights_statement_version__isnull', True)), models.Q(('publication_basis__in', ('author', 'authorized_distributor')), ('rights_confirmed_at__isnull', False), ('rights_statement_version__isnull', False)), _connector='OR'), name='knowledge_book_rights_fields_consistent'),
        ),
    ]
