name: openpage-n
services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command:   #временные ограничения из-за сервера
      - postgres
      - -c
      - max_connections=30
      - -c
      - shared_buffers=256MB
    mem_limit: 1536m
    cpus: 1.0
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  backend:
    image: ghcr.io/ratcker/openpage-backend:main
    env_file: 
      - .env.prod
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - django_static:/app/staticfiles
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/health/')"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  frontend:
    image: ghcr.io/ratcker/openpage-frontend:main
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
    restart: unless-stopped

  gateway:
    image: caddy:2-alpine
    ports:
      - "443:443"
      - "80:80"
      - "443:443/udp"
      - "8081:8081"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - django_static:/srv/django-static:ro
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    restart: unless-stopped

  minio:
    image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:?not set}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?not set}
      MINIO_MEMLIMIT: 768MiB
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    mem_limit: 1g
    cpus: 1.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    restart: unless-stopped

  minio-init:
    image: quay.io/minio/mc:RELEASE.2025-08-13T08-35-41Z
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:?not set}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?not set}
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL:?not set}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME:?not set}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID:?not set}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY:?not set}
    volumes:
      - ./minio/init.sh:/init.sh:ro
    entrypoint: ["/bin/sh", "/init.sh"]
    restart: "no"


volumes:
  postgres_data:
  minio_data:
  caddy_data:
  caddy_config:
  django_static:
