# Generated by Django 5.2.16 on 2026-09-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='CacheEntry',
            fields=[
                (
                    'cache_key',
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ('value', models.TextField()),
                ('expires', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'openpage_cache',
                'default_permissions': (),
            },
        ),
    ]
